# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'kde/pim/akonadi' : '@same'
    'kde/pim/mailcommon' : '@same'
    'kde/pim/mailimporter' : '@same'
    'kde/pim/pimcommon' : '@same'
