# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'pim/akonadi' : '@same'
    'pim/mailcommon' : '@same'
    'pim/mailimporter' : '@same'
    'pim/pimcommon' : '@same'
