# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'kde/pim/akonadi' : '@latest'
    'kde/pim/mailcommon' : '@latest'
    'kde/pim/mailimporter' : '@latest'
    'kde/pim/pimcommon' : '@latest'
